# Generated by Django 2.0.2 on 2018-03-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follows', to='medium.UserProfile'),
        ),
    ]
