# Generated by Django 2.0.2 on 2018-03-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0002_auto_20180308_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topics_raw',
        ),
    ]
