# Generated by Django 2.0.2 on 2018-03-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0003_remove_post_topics_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed_users',
            field=models.TextField(blank=True),
        ),
    ]
