# Generated by Django 2.0.2 on 2018-03-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0003_auto_20180306_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_from_post', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='posts')),
            ],
        ),
    ]
