# Generated by Django 2.0.2 on 2018-03-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0005_auto_20180309_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed_topics',
            field=models.TextField(blank=True),
        ),
    ]
