# Generated by Django 2.0.2 on 2018-03-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0005_auto_20180306_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
