# Generated by Django 2.0.2 on 2018-03-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0006_userprofile_followed_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='follows', to='medium.UserProfile'),
        ),
    ]
