# Generated by Django 2.0.2 on 2018-03-07 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0006_post_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='posts')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_image', to='medium.FeaturedImage'),
        ),
    ]
