# Generated by Django 2.0.2 on 2018-03-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0007_auto_20180307_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
